runtime: nodejs16

env_variables:
  PORT: 3000
  SECRET_KEY: 'thisismysecrctekeyfhrgfgrfrty84fwir767'
  WSPORT: 4040
  KMSURI: "ws://35.190.197.200:8888/kurento"
  # DB_USER: "root"
  # DB_NAME: "database"
  # DB_PASS: "xyz1234pbj"
  # DB_INSTANCE: "project-name:us-central1:sql-instance"
  # TESTVAR: "hehehe"
  # TWILIO_SID: "XYZ1234PBJ"
  # TWILIO_AUTH_TOKEN: "XYZ1234PBJ"
  # GOOGLE_CLIENT_ID: "xyz1234PBJ.apps.googleusercontent.com"
  # GOOGLE_CLIENT_SECRET: "xyz1234-PBJ"