FROM kurento/kurento-media-server:6.18.0

# Copy configuration files
COPY config/kurento.conf.json /etc/kurento/kurento.conf.json
# Copy TLS certificate
COPY config/cert+key.pem /etc/kurento/cert+key.pem